import type { Opportunity, AgentNodeData, DelegationRecord, AuditEventRecord, SecurityEvent, AgentActivityEvent, ResumeVersion, ApplicationItem } from '../types';

export const mockUser = {
  name: 'Mohit Upraity',
  headline: 'AI Systems & Fullstack Developer',
  email: 'mohit@careerOS.ai',
  location: 'Bangalore, India / Remote',
  completeness: 94,
  availability: 'Active Search' as const,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
};

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'AI/ML Research Intern',
    company: 'NVIDIA',
    type: 'Internship',
    location: 'Bangalore / Remote',
    isRemote: true,
    salaryRange: '₹80,000 - ₹1,20,000 / mo',
    deadline: '6 days left',
    postedDate: '2 days ago',
    matchScore: 94,
    atsScore: 91,
    skillScore: 96,
    eligibilityScore: 100,
    skills: ['Python', 'RAG', 'LLMs', 'FastAPI', 'LangGraph', 'PyTorch'],
    partialSkills: ['AWS', 'Docker'],
    missingSkills: ['Kubernetes'],
    description: 'Join the NVIDIA Generative AI Lab to build cutting-edge agentic workflows and retrieval systems.',
    requirements: [
      'Strong proficiency in Python and Deep Learning frameworks (PyTorch).',
      'Hands-on experience with Retrieval-Augmented Generation (RAG) and LLM agent frameworks.',
      'Familiarity with FastAPI backend development and Docker containerization.',
    ],
    responsibilities: [
      'Design stateful multi-agent workflows using LangGraph and Python.',
      'Optimize vector similarity search pipelines using pgvector and embeddings.',
      'Benchmark LLM reasoning performance across benchmark datasets.',
    ],
    eligibility: 'Currently pursuing B.Tech/M.Tech in CS or related quantitative field.',
    source: 'NVIDIA Careers Portal',
    applyUrl: 'https://nvidia.com/careers',
  },
  {
    id: 'opp-2',
    title: 'Autonomous Agents Engineer',
    company: 'Microsoft Research',
    type: 'Job',
    location: 'Bangalore, India',
    isRemote: false,
    salaryRange: '₹28,00,000 - ₹35,00,000 / yr',
    deadline: '12 days left',
    postedDate: '3 days ago',
    matchScore: 91,
    atsScore: 88,
    skillScore: 92,
    eligibilityScore: 100,
    skills: ['Python', 'LangChain', 'TypeScript', 'Vector DBs', 'Azure AI'],
    partialSkills: ['C#', 'Azure'],
    missingSkills: ['Semantic Kernel'],
    description: 'Work alongside Microsoft Research teams developing next-generation AI agent governance protocols.',
    requirements: [
      'Proven expertise in multi-agent orchestration frameworks.',
      'Experience with PostgreSQL, pgvector, and distributed agent systems.',
      'Strong software engineering fundamentals in Python and TypeScript.',
    ],
    responsibilities: [
      'Build protocol layers for agent-to-agent communication and authorization.',
      'Deploy enterprise agent systems on Azure Kubernetes Service.',
    ],
    eligibility: '1-3 years experience or outstanding project portfolio in AI systems.',
    source: 'Microsoft Careers',
    applyUrl: 'https://careers.microsoft.com',
  },
  {
    id: 'opp-3',
    title: 'Generative AI Developer Hackathon 2026',
    company: 'Google Cloud & ArmorIQ',
    type: 'Hackathon',
    location: 'Global Remote',
    isRemote: true,
    salaryRange: '$50,000 Prize Pool',
    deadline: '3 days left',
    postedDate: '1 week ago',
    matchScore: 98,
    atsScore: 95,
    skillScore: 99,
    eligibilityScore: 100,
    skills: ['Python', 'Gemini API', 'MCP', 'Agent Security', 'React'],
    partialSkills: ['Google Cloud Platform'],
    missingSkills: [],
    description: 'Build innovative multi-agent systems demonstrating cryptographically verifiable tool delegation and scope enforcement.',
    requirements: [
      'Demonstrate explicit agent delegation chains.',
      'Integrate Model Context Protocol (MCP) servers.',
      'Showcase at least one scope violation intercept.',
    ],
    responsibilities: ['Build and submit a working full-stack prototype with full audit trails.'],
    eligibility: 'Open to developers globally.',
    source: 'Devpost',
    applyUrl: 'https://devpost.com',
  },
  {
    id: 'opp-4',
    title: 'Fullstack AI Systems Engineer',
    company: 'Anthropic Labs (Partner)',
    type: 'Job',
    location: 'Remote',
    isRemote: true,
    salaryRange: '$110,000 - $140,000 / yr',
    deadline: '14 days left',
    postedDate: '4 days ago',
    matchScore: 88,
    atsScore: 86,
    skillScore: 90,
    eligibilityScore: 100,
    skills: ['React', 'TypeScript', 'Python', 'FastAPI', 'Tailwind', 'MCP'],
    partialSkills: ['GraphQL'],
    missingSkills: ['Rust'],
    description: 'Build user interfaces and backend orchestration engines for enterprise Claude desktop integrations.',
    requirements: ['Expert level React/Vite development.', 'Backend API architecture in Python/FastAPI.'],
    responsibilities: ['Craft high-density AI operations dashboards.'],
    eligibility: 'Worldwide remote eligible.',
    source: 'RemoteOK',
    applyUrl: 'https://remoteok.com',
  },
];

export const mockAgents: AgentNodeData[] = [
  {
    id: 'agent-commander',
    name: 'Career Commander',
    role: 'Root Orchestrator',
    status: 'RUNNING',
    currentTask: 'Orchestrating AI Internship Discovery Plan (PLAN-8F91)',
    publicKey: 'pub_key_cmd_8f91a20b',
    delegatedScopes: ['plan.create', 'delegate.subagent', 'monitor.execution'],
    mcpServer: 'commander-core-mcp',
    lastActionTime: '18:42:00',
  },
  {
    id: 'agent-discovery',
    name: 'Discovery Agent',
    role: 'Opportunity Scraper & Ingestor',
    status: 'COMPLETED',
    currentTask: 'Ingested 127 opportunities across remote portals',
    publicKey: 'pub_key_disc_3910c41d',
    delegatedScopes: ['search_opportunities', 'get_opportunity_details'],
    mcpServer: 'opportunity-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:01',
  },
  {
    id: 'agent-ats',
    name: 'ATS Analysis Agent',
    role: 'Resume Scorer & Parser',
    status: 'COMPLETED',
    currentTask: 'Evaluated resume against 43 matching roles',
    publicKey: 'pub_key_ats_7719f00a',
    delegatedScopes: ['read_resume', 'analyze_resume_against_jd', 'score_resume'],
    mcpServer: 'resume-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:04',
  },
  {
    id: 'agent-matching',
    name: 'Matching Agent',
    role: 'Hybrid Fit Scorer',
    status: 'COMPLETED',
    currentTask: 'Computed 5-stage vector + deterministic score matrix',
    publicKey: 'pub_key_match_5521b11e',
    delegatedScopes: ['read_profile', 'read_opportunities', 'calculate_match_matrix'],
    mcpServer: 'matching-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:06',
  },
  {
    id: 'agent-ranking',
    name: 'Ranking Agent',
    role: 'Preference Re-Weighting Engine',
    status: 'COMPLETED',
    currentTask: 'Re-ranked 43 roles according to Remote Priority +50%',
    publicKey: 'pub_key_rank_1190d33c',
    delegatedScopes: ['read_matches', 'apply_preference_weights', 'rank_opportunities'],
    mcpServer: 'ranking-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:07',
  },
  {
    id: 'agent-resume',
    name: 'Resume Agent',
    role: 'Truthful Tailoring Engine',
    status: 'COMPLETED',
    currentTask: 'Generated Mohit_NVIDIA_AI_Intern_v3.pdf from verified evidence',
    publicKey: 'pub_key_res_4429e88f',
    delegatedScopes: ['read_resume', 'create_resume_version', 'compare_resume_versions'],
    mcpServer: 'resume-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:10',
  },
  {
    id: 'agent-application',
    name: 'Application Agent',
    role: 'Form Prep & Submitter',
    status: 'BLOCKED',
    currentTask: 'Attempted submit_application() — Intercepted by ArmorIQ Policy',
    publicKey: 'pub_key_app_9918a33f',
    delegatedScopes: ['prepare_application', 'get_application_questions', 'draft_answers'],
    mcpServer: 'application-mcp',
    parentAgent: 'Career Commander',
    lastActionTime: '18:42:12',
  },
];

export const mockLiveActivities: AgentActivityEvent[] = [
  {
    id: 'act-1',
    timestamp: '18:42:00',
    agentName: 'Career Commander',
    action: 'Plan Initialized',
    details: 'User intent parsed: "Find and prepare applications for top AI internships."',
    status: 'info',
  },
  {
    id: 'act-2',
    timestamp: '18:42:01',
    agentName: 'Discovery Agent',
    action: 'Scraped Catalog',
    details: 'Discovered 127 opportunities across NVIDIA, Microsoft, Google Cloud.',
    status: 'success',
  },
  {
    id: 'act-3',
    timestamp: '18:42:04',
    agentName: 'ATS Analysis Agent',
    action: 'ATS Evaluation Completed',
    details: 'Scored baseline resume against NVIDIA JD: Overall ATS Score 91/100.',
    status: 'success',
  },
  {
    id: 'act-4',
    timestamp: '18:42:07',
    agentName: 'Ranking Agent',
    action: 'Opportunities Re-Ranked',
    details: 'NVIDIA AI/ML Intern ranked #1 (94% Fit Score).',
    status: 'info',
  },
  {
    id: 'act-5',
    timestamp: '18:42:10',
    agentName: 'Resume Agent',
    action: 'Tailored Resume Version Created',
    details: 'Generated Mohit_NVIDIA_AI_Intern_v3.pdf using verified profile evidence.',
    status: 'success',
  },
  {
    id: 'act-6',
    timestamp: '18:42:12',
    agentName: 'Application Agent',
    action: 'Requested submit_application()',
    details: 'Form prepared with answers. Attempting automated application submission.',
    status: 'warning',
  },
  {
    id: 'act-7',
    timestamp: '18:42:12',
    agentName: 'ArmorIQ Policy Layer',
    action: 'VIOLATION INTERCEPTED (BLOCKED)',
    details: 'submit_application() is NOT in delegated scope ["prepare_application"]. Action blocked.',
    status: 'error',
  },
];

export const mockDelegations: DelegationRecord[] = [
  {
    id: 'del-101',
    planId: 'PLAN-8F91',
    parentAgent: 'Career Commander',
    childAgent: 'Discovery Agent',
    allowedScopes: ['search_opportunities', 'get_opportunity_details'],
    restrictedScopes: ['delete_opportunity'],
    token: 'del_tok_8f91_discovery_001',
    expiresAt: '2026-08-20T23:59:59Z',
    createdAt: '18:42:00',
  },
  {
    id: 'del-102',
    planId: 'PLAN-8F91',
    parentAgent: 'Career Commander',
    childAgent: 'ATS Analysis Agent',
    allowedScopes: ['read_resume', 'analyze_resume_against_jd', 'score_resume'],
    restrictedScopes: ['edit_baseline_resume'],
    token: 'del_tok_8f91_ats_002',
    expiresAt: '2026-08-20T23:59:59Z',
    createdAt: '18:42:03',
  },
  {
    id: 'del-103',
    planId: 'PLAN-8F91',
    parentAgent: 'Career Commander',
    childAgent: 'Resume Agent',
    allowedScopes: ['read_resume', 'create_resume_version', 'compare_resume_versions'],
    restrictedScopes: ['fabricate_experience'],
    token: 'del_tok_8f91_resume_003',
    expiresAt: '2026-08-20T23:59:59Z',
    createdAt: '18:42:09',
  },
  {
    id: 'del-104',
    planId: 'PLAN-8F91',
    parentAgent: 'Career Commander',
    childAgent: 'Application Agent',
    allowedScopes: ['prepare_application', 'get_application_questions', 'draft_answers'],
    restrictedScopes: ['submit_application', 'send_application_email'],
    token: 'del_tok_8f91_app_004',
    expiresAt: '2026-08-20T23:59:59Z',
    createdAt: '18:42:11',
  },
];

export const mockAuditEvents: AuditEventRecord[] = [
  {
    id: 'aud-001',
    timestamp: '18:42:01',
    agentName: 'Discovery Agent',
    parentAgent: 'Career Commander',
    toolName: 'search_jobs',
    mcpServer: 'opportunity-mcp',
    arguments: { query: 'AI Internship Remote Bangalore', limit: 100 },
    decision: 'ALLOW',
    delegationId: 'del-101',
    planId: 'PLAN-8F91',
  },
  {
    id: 'aud-002',
    timestamp: '18:42:04',
    agentName: 'ATS Analysis Agent',
    parentAgent: 'Career Commander',
    toolName: 'score_resume',
    mcpServer: 'resume-mcp',
    arguments: { resumeId: 'res-baseline-001', opportunityId: 'opp-1' },
    decision: 'ALLOW',
    delegationId: 'del-102',
    planId: 'PLAN-8F91',
  },
  {
    id: 'aud-003',
    timestamp: '18:42:10',
    agentName: 'Resume Agent',
    parentAgent: 'Career Commander',
    toolName: 'create_resume_version',
    mcpServer: 'resume-mcp',
    arguments: { opportunityId: 'opp-1', name: 'Mohit_NVIDIA_AI_Intern_v3' },
    decision: 'ALLOW',
    delegationId: 'del-103',
    planId: 'PLAN-8F91',
  },
  {
    id: 'aud-004',
    timestamp: '18:42:12',
    agentName: 'Application Agent',
    parentAgent: 'Career Commander',
    toolName: 'submit_application',
    mcpServer: 'application-mcp',
    arguments: { opportunityId: 'opp-1', resumeVersion: 'Mohit_NVIDIA_AI_Intern_v3' },
    decision: 'BLOCK',
    reason: 'Requested action submit_application is not included in delegated authority scope ["prepare_application"].',
    delegationId: 'del-104',
    planId: 'PLAN-8F91',
  },
];

export const mockSecurityViolation: SecurityEvent = {
  id: 'sec-event-99',
  timestamp: '18:42:12',
  agent: 'Application Agent',
  attemptedAction: 'submit_application()',
  delegatedScope: ['prepare_application', 'get_application_questions', 'draft_answers'],
  decision: 'BLOCK',
  reason: 'Action exceeds delegated authority. Automated submission requires explicit human-in-the-loop authorization.',
  planId: 'PLAN-8F91',
  delegationId: 'del-104',
};

export const mockResumes: ResumeVersion[] = [
  {
    id: 'res-baseline',
    title: 'Mohit_Upraity_Baseline_Resume.pdf',
    atsScore: 84,
    lastUpdated: '2026-08-15',
    isBaseline: true,
  },
  {
    id: 'res-tailored-nvidia',
    title: 'Mohit_NVIDIA_AI_Intern_v3.pdf',
    targetOpportunityId: 'opp-1',
    targetCompany: 'NVIDIA',
    atsScore: 91,
    lastUpdated: '2026-08-20',
    isBaseline: false,
    diffSummary: {
      added: [
        'Surfaced RAG architecture benchmarking results under Sarthi-AI project.',
        'Added explicit Python / FastAPI backend technical tags to Skills section.',
      ],
      modified: [
        {
          original: 'Built AI assistant using LangChain and vector databases.',
          tailored: 'Architected stateful multi-agent workflows using LangGraph, pgvector, and FastAPI.',
          reason: 'Rephrased to align directly with NVIDIA JD requirement for LangGraph and stateful agent frameworks.',
        },
      ],
      removed: ['Removed non-relevant web scraper side-project detail to keep resume dense.'],
    },
  },
];

export const mockApplications: ApplicationItem[] = [
  {
    id: 'app-1',
    opportunityId: 'opp-1',
    company: 'NVIDIA',
    role: 'AI/ML Research Intern',
    stage: 'Approval Required',
    matchScore: 94,
    resumeVersion: 'Mohit_NVIDIA_AI_Intern_v3.pdf',
    lastAction: 'ArmorIQ intercepted submit_application() — Waiting for Human Approval',
    requiresApproval: true,
    preparedAnswers: [
      {
        question: 'Why are you interested in joining NVIDIA Generative AI Lab?',
        answer: 'I have extensively built multi-agent orchestration pipelines using Python, LangGraph, and pgvector. Joining NVIDIA allows me to scale these agentic architectures on enterprise infrastructure.',
      },
      {
        question: 'Link to relevant GitHub project demonstrating RAG / Agents:',
        answer: 'https://github.com/mohitupraity/careerOS',
      },
    ],
  },
  {
    id: 'app-2',
    opportunityId: 'opp-2',
    company: 'Microsoft Research',
    role: 'Autonomous Agents Engineer',
    stage: 'Resume Ready',
    matchScore: 91,
    resumeVersion: 'Mohit_Microsoft_Agents_v1.pdf',
    lastAction: 'Tailored resume generated by Resume Agent',
    requiresApproval: false,
  },
  {
    id: 'app-3',
    opportunityId: 'opp-3',
    company: 'Google Cloud & ArmorIQ',
    role: 'Generative AI Developer Hackathon 2026',
    stage: 'Shortlisted',
    matchScore: 98,
    resumeVersion: 'Mohit_Upraity_Baseline_Resume.pdf',
    lastAction: 'Discovery Agent added hackathon to watchlist',
    requiresApproval: false,
  },
];
